name: Install package

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pkg-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Create package
        run: |
          # python setup.py check --metadata --strict
          python setup.py sdist
      - name: Check package
        run: |
          pip install twine==4.0.0
          twine check dist/*
          python setup.py clean

  pkg-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # max-parallel: 6
      matrix:
        # PyTorch 1.5 is failing on Win and bolts requires torchvision>=0.5
        os: [ubuntu-20.04, macOS-12]  # , windows-2022
        # fixme
        python-version: [3.7]  # , 3.8

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create package
        run: |
          # python setup.py check --metadata --strict
          python setup.py sdist
      - name: Install package
        run: |
          pip install virtualenv
          virtualenv vEnv
          source vEnv/bin/activate
          pip install dist/*
          cd .. & python -c "import pytorch_lightning as pl ; print(pl.__version__)"
          cd .. & python -c "import flash ; print(flash.__version__)"
          deactivate
          rm -rf vEnv
